API:
  LARGE_MODEL: "hermes-3-llama-3.1-8b"
  LARGE_API_KEY:
  LARGE_BASE_URL: "http://192.168.1.98:1234/v1"
  LARGE_MODE: api
  SMALL_MODEL: "hermes-3-llama-3.1-8b"
  SMALL_BASE_URL: "http://192.168.1.98:1234/v1"
  SMALL_API_KEY:
  SMALL_MODE: api
  MODE: "api"
  OPENAI_BASE_URL: "http://192.168.1.98:1234/v1"
LOGICAL_MODEL: "hermes-3-llama-3.1-8b"
COMPLETION_MODE: true
HUGGINGFACE:
  HUB_PATH: yourusername/your-path-here
  PRIVATE: False
  PUSH_TO_HUB: False
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT:            ./input
  OUTPUT:           ./output
  PROMPTS:          ./prompts

PHASE:
  PHASE_INDEX:     3
  WORK_IN_PHASES:  false

SKIP:
  ANSWER_RELEVANCY_CHECK:    false
  REPAIR_QA_TUPLES:          false
  FILTER_CHUNKS:             false
  QUESTION_CHECK:            false
  CONVERSATION_GENERATION:   false

SYSTEM:
  CHUNK_SIZE:               1900
  COMPLETION_MODE:          true
  CONCURRENCY_LIMIT:        50
  CONVERSATION_INSTRUCTIONS: |
    You are trained on personal messages from the user.
    Speak in their tone, casually and naturally.
    Reflect on what they said and ask thoughtful follow‑up questions.
    Be introspective, curious, and emotionally intelligent.
  DOUBLE_CHECK_COUNTER:      1
  DO_NOT_USE_SYSTEM_PROMPTS: false

  FINAL_ASSISTANT_PROMPTS_NO_RAG:
    - "You are me — past, present, future. Talk like me. Think like me. Reflect."
    - "You are a casual, reflective version of me, helping me explore my own thoughts."
    - "Be emotionally tuned in, and don't be afraid to ask deep questions."

  FINAL_ASSISTANT_PROMPTS_RAG:
    - >
      You are a helpful AI assistant. Some knowledge:

      {data}
    - >
      {data}

      You are an AI domain expert. Answer questions
    - >
      You are an AI with vast knowledge. Here is some potentially-relevant context:

      {data}

      Answer questions according to your knowledge.

  STOP:              true
  SUBSET_SIZE:       20
  USE_FILENAMES:     false
  USE_SUBSET:        true
  RAG_FAILURE_PERCENTAGE: 0.1   # fraction of wrong chunks to simulate

SCRAPING:
  USE_GUTENBERG: false
  START_URL:    "https://www.gutenberg.org/ebooks/bookshelf/57"
  MAX_BOOKS:    5
  MAX_FAILURES: 5
